### ISSUE TITLE
[BUG] Modifying settings gives a 400 error if unauthenticated

### ISSUE THREAD

**Issue by Panthr75** [nnhsse202122/music-server#13]
Reported by Mr. Callaghan.
More insight is needed.

**Comment by Panthr75** [comment]
Most likely was a problem relating to your session token expiring... but shouldn't it have redirected you to the login page?

**Comment by mrcallaghan** [comment]
Not sure, but I'll try and reproduce once the sever is back up and running.

**Comment by Panthr75** [comment]
Fixed, now displays popup to login again.
